In [1]:
from pathlib import Path

import pandas as pd
from scipy.stats import spearmanr

from common_generate_predictions import load_data
from common_extra_processing import build_id

In [2]:
path_to_file = "/data/fzamora/cv-experiments-lscd-all-hyperparameter/wsbm/mixtral"

In [3]:
dataset = "dwug_en"

In [4]:
p = Path(path_to_file)
p.exists()

True

In [5]:
data_to_be_concatenated = []

for d in (p / f"{dataset}").iterdir():
    if d.is_dir() is True:
        data = pd.read_csv(f"{d}/results_testing_set.csv")
        data_to_be_concatenated.append(data)

In [6]:
data = pd.concat(data_to_be_concatenated, axis=0, ignore_index=True)
display(data)

,word,jsd,clusters_to_freq1,clusters_to_freq2,parameters
0,lass_nn,0.238446,"{0: 14, 5: 9, 13: 2, 8: 2, 1: 9, 10: 2, 2: 11,...","{0: 13, 5: 9, 13: 1, 8: 6, 1: 12, 10: 4, 2: 10...","{'fill_diagonal': True, 'normalize': False, 'p..."
1,stab_nn,0.530879,"{22: 0, 4: 11, 8: 2, 14: 2, 23: 2, 6: 5, 33: 0...","{22: 2, 4: 1, 8: 4, 14: 1, 23: 0, 6: 2, 33: 1,...","{'fill_diagonal': True, 'normalize': False, 'p..."
2,part_nn,0.547844,"{0: 8, 3: 5, 22: 1, 11: 3, 12: 2, 7: 2, 4: 7, ...","{0: 12, 3: 6, 22: 1, 11: 0, 12: 1, 7: 4, 4: 4,...","{'fill_diagonal': True, 'normalize': False, 'p..."
3,twist_nn,0.543472,"{3: 3, 38: 0, 23: 0, 16: 3, 24: 1, 7: 4, 0: 9,...","{3: 9, 38: 1, 23: 2, 16: 0, 24: 1, 7: 3, 0: 10...","{'fill_diagonal': True, 'normalize': False, 'p..."
4,pin_vb,0.341964,"{3: 11, 1: 14, 16: 2, 4: 10, 8: 2, 0: 23, 9: 1...","{3: 8, 1: 14, 16: 1, 4: 3, 8: 2, 0: 17, 9: 3, ...","{'fill_diagonal': True, 'normalize': False, 'p..."
5,tip_vb,0.513736,"{28: 0, 18: 2, 40: 0, 41: 1, 2: 6, 8: 4, 19: 1...","{28: 2, 18: 1, 40: 1, 41: 0, 2: 5, 8: 0, 19: 2...","{'fill_diagonal': True, 'normalize': False, 'p..."
6,attack_nn,0.324930,"{0: 13, 3: 15, 1: 8, 2: 12, 7: 8, 9: 1, 10: 1,...","{0: 10, 3: 5, 1: 14, 2: 10, 7: 7, 9: 5, 10: 5,...","{'fill_diagonal': True, 'normalize': False, 'p..."
7,graft_nn,0.491407,"{1: 12, 18: 0, 7: 2, 6: 3, 22: 1, 11: 4, 13: 2...","{1: 5, 18: 3, 7: 7, 6: 7, 22: 1, 11: 3, 13: 4,...","{'fill_diagonal': True, 'normalize': False, 'p..."
8,thump_nn,0.282976,"{6: 5, 10: 2, 5: 10, 8: 4, 0: 10, 3: 11, 1: 13...","{6: 7, 10: 1, 5: 3, 8: 6, 0: 26, 3: 11, 1: 14,...","{'fill_diagonal': True, 'normalize': False, 'p..."
9,lane_nn,0.272511,"{14: 1, 1: 13, 0: 17, 3: 7, 4: 10, 12: 0, 2: 1...","{14: 1, 1: 15, 0: 17, 3: 11, 4: 8, 12: 3, 2: 9...","{'fill_diagonal': True, 'normalize': False, 'p..."
10,face_nn,0.270438,"{0: 18, 4: 10, 2: 9, 5: 8, 6: 11, 3: 9, 7: 3, ...","{0: 10, 4: 7, 2: 13, 5: 9, 6: 3, 3: 10, 7: 7, ...","{'fill_diagonal': True, 'normalize': False, 'p..."
11,plane_nn,0.390844,"{2: 6, 3: 11, 1: 9, 0: 12, 8: 3, 15: 2, 5: 5, ...","{2: 12, 3: 7, 1: 10, 0: 8, 8: 7, 15: 0, 5: 9, ...","{'fill_diagonal': True, 'normalize': False, 'p..."
12,head_nn,0.497631,"{6: 1, 10: 0, 3: 4, 7: 0, 4: 7, 32: 1, 1: 18, ...","{6: 3, 10: 2, 3: 16, 7: 3, 4: 10, 32: 0, 1: 12...","{'fill_diagonal': True, 'normalize': False, 'p..."
13,multitude_nn,0.308202,"{3: 5, 6: 3, 2: 15, 8: 1, 7: 4, 1: 21, 9: 4, 4...","{3: 13, 6: 9, 2: 14, 8: 5, 7: 7, 1: 11, 9: 2, ...","{'fill_diagonal': True, 'normalize': False, 'p..."
14,land_nn,0.250754,"{1: 15, 0: 18, 10: 3, 3: 12, 2: 16, 6: 4, 12: ...","{1: 15, 0: 15, 10: 2, 3: 11, 2: 9, 6: 8, 12: 2...","{'fill_diagonal': True, 'normalize': False, 'p..."
15,stroke_vb,0.364246,"{17: 0, 2: 11, 1: 9, 8: 4, 0: 27, 3: 11, 7: 3,...","{17: 2, 2: 8, 1: 12, 8: 2, 0: 23, 3: 8, 7: 4, ...","{'fill_diagonal': True, 'normalize': False, 'p..."
16,chairman_nn,0.296989,"{0: 22, 1: 14, 6: 6, 4: 8, 3: 15, 5: 6, 2: 15,...","{0: 18, 1: 19, 6: 5, 4: 12, 3: 6, 5: 11, 2: 14...","{'fill_diagonal': True, 'normalize': False, 'p..."
17,relationship_nn,0.231695,"{2: 8, 6: 10, 3: 10, 11: 2, 0: 18, 12: 3, 13: ...","{2: 13, 6: 2, 3: 10, 11: 2, 0: 15, 12: 1, 13: ...","{'fill_diagonal': True, 'normalize': False, 'p..."
18,player_nn,0.330066,"{10: 1, 0: 20, 19: 1, 3: 8, 9: 2, 1: 15, 4: 10...","{10: 2, 0: 13, 19: 1, 3: 8, 9: 2, 1: 15, 4: 4,...","{'fill_diagonal': True, 'normalize': False, 'p..."
19,ball_nn,0.434910,"{0: 10, 11: 1, 12: 4, 2: 10, 15: 4, 6: 4, 1: 9...","{0: 10, 11: 4, 12: 1, 2: 6, 15: 0, 6: 5, 1: 11...","{'fill_diagonal': True, 'normalize': False, 'p..."
20,gas_nn,0.242659,"{0: 19, 2: 11, 8: 3, 9: 1, 1: 18, 3: 11, 6: 7,...","{0: 22, 2: 13, 8: 2, 9: 4, 1: 18, 3: 11, 6: 4,...","{'fill_diagonal': True, 'normalize': False, 'p..."
21,prop_nn,0.522733,"{17: 2, 4: 6, 18: 0, 2: 12, 9: 3, 3: 5, 5: 5, ...","{17: 1, 4: 3, 18: 3, 2: 5, 9: 3, 3: 6, 5: 4, 1...","{'fill_diagonal': True, 'normalize': False, 'p..."
22,word_nn,0.213948,"{3: 11, 1: 13, 4: 9, 5: 6, 0: 16, 14: 0, 6: 5,...","{3: 12, 1: 13, 4: 10, 5: 7, 0: 17, 14: 3, 6: 3...","{'fill_diagonal': True, 'normalize': False, 'p..."
23,contemplation_nn,0.218579,"{5: 7, 2: 11, 4: 8, 0: 12, 3: 10, 6: 10, 7: 8,...","{5: 8, 2: 12, 4: 8, 0: 16, 3: 10, 6: 4, 7: 6, ...","{'fill_diagonal': True, 'normalize': False, 'p..."
24,fiction_nn,0.215485,"{8: 5, 5: 9, 3: 8, 2: 16, 6: 7, 0: 14, 13: 1, ...","{8: 4, 5: 6, 3: 11, 2: 12, 6: 8, 0: 18, 13: 1,...","{'fill_diagonal': True, 'normalize': False, 'p..."
25,ounce_nn,0.311768,"{0: 18, 13: 0, 4: 11, 21: 0, 5: 8, 1: 13, 18: ...","{0: 11, 13: 3, 4: 9, 21: 1, 5: 6, 1: 13, 18: 2...","{'fill_diagonal': True, 'normalize': False, 'p..."
26,risk_nn,0.244471,"{1: 12, 8: 9, 2: 6, 0: 19, 3: 10, 6: 8, 10: 2,...","{1: 15, 8: 2, 2: 16, 0: 10, 3: 11, 6: 4, 10: 2...","{'fill_diagonal': True, 'normalize': False, 'p..."
27,rag_nn,0.401863,"{29: 0, 2: 9, 21: 2, 1: 11, 11: 3, 5: 4, 16: 3...","{29: 1, 2: 12, 21: 0, 1: 12, 11: 1, 5: 7, 16: ...","{'fill_diagonal': True, 'normalize': False, 'p..."
28,donkey_nn,0.291119,"{11: 0, 7: 8, 0: 12, 9: 5, 10: 3, 6: 7, 3: 10,...","{11: 3, 7: 2, 0: 14, 9: 2, 10: 4, 6: 9, 3: 12,...","{'fill_diagonal': True, 'normalize': False, 'p..."
29,savage_nn,0.136598,"{6: 7, 3: 8, 2: 14, 5: 10, 8: 3, 4: 10, 0: 21,...","{6: 7, 3: 14, 2: 14, 5: 8, 8: 2, 4: 10, 0: 19,...","{'fill_diagonal': True, 'normalize': False, 'p..."
30,circle_vb,0.296252,"{9: 3, 11: 2, 0: 13, 14: 2, 5: 7, 12: 2, 1: 14...","{9: 3, 11: 3, 0: 12, 14: 2, 5: 6, 12: 3, 1: 10...","{'fill_diagonal': True, 'normalize': False, 'p..."
31,tree_nn,0.249256,"{1: 20, 2: 18, 3: 12, 4: 9, 0: 14, 9: 3, 5: 5,...","{1: 16, 2: 15, 3: 16, 4: 9, 0: 27, 9: 1, 5: 8,...","{'fill_diagonal': True, 'normalize': False, 'p..."
32,record_nn,0.481512,"{10: 0, 7: 6, 3: 10, 11: 1, 8: 4, 2: 11, 4: 11...","{10: 3, 7: 2, 3: 11, 11: 2, 8: 1, 2: 11, 4: 7,...","{'fill_diagonal': True, 'normalize': False, 'p..."
33,edge_nn,0.375936,"{3: 12, 11: 0, 17: 1, 6: 7, 1: 16, 4: 3, 18: 1...","{3: 9, 11: 3, 17: 1, 6: 4, 1: 14, 4: 12, 18: 1...","{'fill_diagonal': True, 'normalize': False, 'p..."
34,quilt_nn,0.187707,"{5: 7, 4: 9, 1: 13, 3: 10, 6: 7, 2: 13, 11: 4,...","{5: 9, 4: 9, 1: 19, 3: 10, 6: 9, 2: 12, 11: 0,...","{'fill_diagonal': True, 'normalize': False, 'p..."
35,bag_nn,0.309068,"{3: 5, 1: 10, 4: 12, 0: 20, 6: 8, 9: 3, 2: 11,...","{3: 14, 1: 21, 4: 6, 0: 15, 6: 8, 9: 2, 2: 14,...","{'fill_diagonal': True, 'normalize': False, 'p..."
36,bit_nn,0.412070,"{2: 12, 6: 2, 5: 3, 7: 2, 8: 2, 1: 17, 9: 2, 3...","{2: 17, 6: 1, 5: 1, 7: 1, 8: 1, 1: 14, 9: 1, 3...","{'fill_diagonal': True, 'normalize': False, 'p..."

In [7]:
predictions = data.set_index("word")["jsd"].to_dict()
predictions

{'lass_nn': 0.238445922780226,
 'stab_nn': 0.5308793158241807,
 'part_nn': 0.5478441439298861,
 'twist_nn': 0.5434724309824103,
 'pin_vb': 0.3419637007860673,
 'tip_vb': 0.5137358841219615,
 'attack_nn': 0.3249302808690881,
 'graft_nn': 0.4914068997983495,
 'thump_nn': 0.2829763408011829,
 'lane_nn': 0.2725114144191304,
 'face_nn': 0.2704377171701263,
 'plane_nn': 0.3908444798943027,
 'head_nn': 0.497631361558818,
 'multitude_nn': 0.3082015593606987,
 'land_nn': 0.2507544661778766,
 'stroke_vb': 0.3642464818729104,
 'chairman_nn': 0.2969886010820624,
 'relationship_nn': 0.2316951407812599,
 'player_nn': 0.3300663754098532,
 'ball_nn': 0.4349103908013926,
 'gas_nn': 0.2426586555948336,
 'prop_nn': 0.5227325490363068,
 'word_nn': 0.2139484830109836,
 'contemplation_nn': 0.2185790783928909,
 'fiction_nn': 0.2154854944461908,
 'ounce_nn': 0.3117677173001769,
 'risk_nn': 0.2444705096271088,
 'rag_nn': 0.4018627554852857,
 'donkey_nn': 0.2911185695028587,
 'savage_nn': 0.1365980332744574,
 'circle_vb': 0.2962517891087771,
 'tree_nn': 0.2492557300182022,
 'record_nn': 0.4815122575464302,
 'edge_nn': 0.3759361179167821,
 'quilt_nn': 0.1877068362311176,
 'bag_nn': 0.3090679132258091,
 'bit_nn': 0.4120696511638866}

In [8]:
target_words = data["word"].unique()
gold_data = pd.read_csv("../test_data_en.csv", sep="\t")
gold_data = gold_data[gold_data["lemma"].isin(target_words)]
gold_data_change_graded = gold_data.set_index("lemma")["change_graded"].to_dict()
gold_data_change_graded

{'attack_nn': 0.2352229402,
 'bag_nn': 0.0013100389,
 'ball_nn': 0.4585684984,
 'bit_nn': 0.3465632472,
 'chairman_nn': 0.0,
 'circle_vb': 0.2377191744,
 'contemplation_nn': 0.070838721,
 'donkey_nn': 0.1007598521,
 'edge_nn': 0.3645569578,
 'face_nn': 0.1857763137,
 'fiction_nn': 0.1244096123,
 'gas_nn': 0.2783037792,
 'graft_nn': 0.5717010642,
 'head_nn': 0.2603654807,
 'land_nn': 0.2277106706,
 'lane_nn': 0.1329105525,
 'lass_nn': 0.2318626707,
 'multitude_nn': 0.1424585835,
 'ounce_nn': 0.1229636843,
 'part_nn': 0.2689550557,
 'pin_vb': 0.2394438117,
 'plane_nn': 0.9154730339,
 'player_nn': 0.3077040091,
 'prop_nn': 0.5962665796,
 'quilt_nn': 0.1231453661,
 'rag_nn': 0.2536585401,
 'record_nn': 0.4113347374,
 'relationship_nn': 0.0562177896,
 'risk_nn': 0.0,
 'savage_nn': 0.0719298616,
 'stab_nn': 0.4291850687,
 'stroke_vb': 0.2056167693,
 'thump_nn': 0.1438151936,
 'tip_vb': 0.5446143922,
 'tree_nn': 0.0,
 'twist_nn': 0.4563854849,
 'word_nn': 0.1640398061}

In [9]:
v1, v2 = [], []

In [10]:
for tw in target_words:
    v1.append(gold_data_change_graded[tw])
    v2.append(predictions[tw])

assert len(v1) == len(v2)

In [11]:
spr, _ = spearmanr(v1, v2)
spr

0.7488736278852801

In [12]:
with open(f"{path_to_file}/{dataset}/final_results.txt", "r") as f_in:
    print(f_in.read())

Avg spr_lscd [train]: 0.8264970238304775
Std spr_lscd [train]: 0.04516538740742362

Avg spr_lscd [testing]: 0.5928571428571429
Std spr_lscd [testing]: 0.14876666049346018

best parameters per fold
  Fold 1 {'fill_diagonal': True, 'normalize': False, 'prompt': 'ct', 'model_hyperparameters': {'distribution': 'discrete-binomial'}}
  Fold 2 {'fill_diagonal': True, 'normalize': False, 'prompt': 'fs', 'model_hyperparameters': {'distribution': 'discrete-binomial'}}
  Fold 3 {'fill_diagonal': True, 'normalize': False, 'prompt': 'zs', 'model_hyperparameters': {'distribution': 'discrete-binomial'}}
  Fold 4 {'fill_diagonal': True, 'normalize': False, 'prompt': 'zs', 'model_hyperparameters': {'distribution': 'discrete-binomial'}}
  Fold 5 {'fill_diagonal': True, 'normalize': False, 'prompt': 'fs', 'model_hyperparameters': {'distribution': 'discrete-binomial'}}

In [13]:
path_to_dwug_es_results = (
    "/data/fzamora/cv-experiments-lscd/wsbm/mixtral/dwug_es/fs"
)

In [14]:
path_to_results = Path(path_to_dwug_es_results)
path_to_results.exists()

True

In [15]:
data_to_be_concatenated = []

In [16]:
for d in path_to_results.iterdir():
    if d.is_dir():
        data_to_be_concatenated.append(pd.read_csv(f"{d}/results_testing_set.csv"))

In [17]:
data = pd.concat(data_to_be_concatenated, ignore_index=True)
predictions = data.set_index("word")["jsd"].to_dict()
predictions

{'disco': 0.0,
 'compasión': 0.0,
 'recordar': 0.0,
 'historia': 0.0,
 'tarea': 0.0,
 'maduro': 0.0,
 'tropical': 0.0,
 'matiz': 0.6497022807926136,
 'cobrar': 0.262534388664034,
 'prima': 0.924660694787462,
 'susceptible': 0.0,
 'capital': 0.0,
 'médula': 0.0,
 'propiamente': 0.0,
 'solicitud': 0.0,
 'variedad': 0.0,
 'actitud': 0.0,
 'impulso': 0.0,
 'recomendar': 0.0,
 'colaborar': 0.0,
 'ataque': 0.0,
 'ausencia': 0.0,
 'fallar': 0.0,
 'historiador': 0.0,
 'pila': 0.0,
 'especulación': 0.0,
 'maravilloso': 0.0,
 'atrás': 0.0,
 'visita': 0.0,
 'educado': 0.0,
 'planta': 0.0,
 'encargado': 0.0,
 'avance': 0.0,
 'pendiente': 0.787717972176712,
 'juguete': 0.0,
 'vuestro': 0.0,
 'indicativo': 0.924660694787462,
 'retroceder': 0.0,
 'elocuente': 0.0,
 'canal': 0.0,
 'declinar': 0.0,
 'diligencia': 0.0,
 'socialista': 0.0,
 'próximo': 0.0,
 'distribuir': 0.0,
 'trato': 0.0,
 'viernes': 0.0,
 'demá': 0.0,
 'metro': 0.0,
 'cólera': 0.0,
 'banco': 0.0,
 'modificado': 0.0,
 'corriente': 0.0,
 'enterar': 0.0,
 'fallecimiento': 0.5438817408634727,
 'nombrar': 0.0,
 'satélite': 0.924660694787462,
 'marco': 0.0,
 'copiar': 0.0,
 'metal': 0.0}

In [18]:
target_words_spanish = data["word"].unique()
gold_data_spanish = pd.read_csv("../test_data_es.csv", sep="\t")
gold_data_spanish_change_graded = gold_data_spanish.set_index("word")[
    "change_graded"
].to_dict()
gold_data_spanish_change_graded

{'actitud': 0.924660694787462,
 'ataque': 0.481434326015839,
 'atrás': 0.159569586509122,
 'ausencia': 0.0,
 'avance': 0.590113006548187,
 'banco': 0.924660694787462,
 'canal': 1.0,
 'capital': 0.446772089340575,
 'cobrar': 0.217259009452276,
 'colaborar': 0.557923045284144,
 'cólera': 0.740806952380577,
 'compasión': 0.0,
 'copiar': 0.459106313807781,
 'corriente': 0.753008193531393,
 'declinar': 0.572362532222144,
 'demá': 0.319381864104736,
 'diligencia': 0.469564643718015,
 'disco': 0.914749624036807,
 'distribuir': 0.0,
 'educado': 0.159569586509122,
 'elocuente': 0.0,
 'encargado': 0.227813872100264,
 'enterar': 0.0,
 'especulación': 0.185296689786368,
 'fallar': 0.171505575857383,
 'fallecimiento': 0.0,
 'historia': 0.0,
 'historiador': 0.0,
 'impulso': 0.159569586509122,
 'indicativo': 1.0,
 'juguete': 0.246987376051603,
 'maduro': 0.19849916170588,
 'maravilloso': 0.0,
 'marco': 1.0,
 'matiz': 0.0,
 'médula': 0.295793409293228,
 'metal': 0.557923045284144,
 'metro': 0.469476812293811,
 'modificado': 0.449423861592608,
 'nombrar': 0.343159459069689,
 'pendiente': 0.781016355149486,
 'pila': 0.583813439451817,
 'planta': 0.719649002723823,
 'prima': 1.0,
 'propiamente': 0.0,
 'próximo': 0.553572200012742,
 'recomendar': 0.434412986839874,
 'recordar': 0.0,
 'retroceder': 0.569065505130796,
 'satélite': 0.924660694787462,
 'socialista': 0.0,
 'solicitud': 0.740806952380577,
 'susceptible': 0.48626412335276,
 'tarea': 0.0,
 'trato': 0.0508892851174599,
 'tropical': 0.371383065001664,
 'variedad': 0.0,
 'viernes': 0.0,
 'visita': 0.159569586509122,
 'vuestro': 0.0}

In [19]:
v1, v2 = [], []

In [20]:
for tw in target_words_spanish:
    v1.append(gold_data_spanish_change_graded[tw])
    v2.append(predictions[tw])

assert len(v1) == len(v2)

In [21]:
spr, _ = spearmanr(v1, v2)
spr

0.18905559273041267

In [22]:
path_to_results = "/data/fzamora/cv-apd-experiments-lscd/{llm}/{dataset}"

In [23]:
for dataset in ["dwug_es", "dwug_en"]:
    print(f"{dataset}:")

    for model in ["llama3.1-8B", "mixtral-8xtb-v0.1"]:
        print(f"  {model}: ", end=" ")

        p = path_to_results.format(llm=model, dataset=dataset)
        data_to_be_concatenated = []
        v1, v2 = [], []

        assert Path(p).exists() is True

        for dir in Path(p).iterdir():
            if dir.is_dir():
                data_to_be_concatenated.append(
                    pd.read_csv(f"{dir}/results_testing_set.csv")
                )

        data = pd.concat(data_to_be_concatenated, axis=0, ignore_index=True)
        predictions = data.set_index("word")["apd"].to_dict()

        for tw in target_words_spanish if dataset == "dwug_es" else target_words:
            v1.append(
                gold_data_spanish_change_graded[tw]
                if dataset == "dwug_es"
                else gold_data_change_graded[tw]
            )
            v2.append(predictions[tw])

        assert len(v1) == len(v2)

        spr, _ = spearmanr(v1, v2)
        print(spr)

        print()

dwug_es:
  llama3.1-8B:  0.3764794096151987

  mixtral-8xtb-v0.1:  0.04538040127700754

dwug_en:
  llama3.1-8B:  0.3357837419523612

  mixtral-8xtb-v0.1:  0.5024899358736253

In [65]:
input = "../input/{llm}/{dataset}/fs"

In [59]:
gold_data_spanish_compare = gold_data_spanish.set_index("word")["COMPARE"].to_dict()

In [73]:
for dataset in ["dwug_en"]:
    print(f"{dataset}:")

    for model in ["llama3.1-8B", "mixtral-8xtb-v0.1"]:
        print(f"  {model}:", end=" ")

        p = Path(input.format(llm=model, dataset=dataset))
        v1, v2 = [], []

        assert p.exists() is True

        data = load_data(p)
        if dataset == "dwug_en":
            data = data.apply(lambda row: build_id(row), axis=1)

        mask_earlier = (data["identifier1"].str.split("_").str[0] == "old") & (
            data["identifier2"].str.split("_").str[0] == "old"
        )
        mask_later = (data["identifier1"].str.split("_").str[0] != "old") & (
            data["identifier2"].str.split("_").str[0] != "old"
        )
        mask_compare = (~mask_earlier & ~mask_later) | (~mask_later & ~mask_earlier)

        data_compare = data[mask_compare]
        data_earlier = data[mask_earlier]
        data_later = data[mask_later]
        
        # pred = data_compare.set_index("word")["score"].to_dict()

        pred_earlier = data_earlier.groupby("word")["score"].mean().reset_index()
        pred_later = data_later.groupby("word")["score"].mean().reset_index()
        pred_compare = data_compare.groupby("word")["score"].mean().reset_index()

        compare_earlier = pred_compare.merge(
            pred_earlier, on="word", suffixes=("_compare", "_earlier")
        )
        compare_earlier_later = compare_earlier.merge(pred_later, on="word")
        compare_earlier_later.rename(columns={"score": "score_later"}, inplace=True)

        # compare_earlier_later["score"] = compare_earlier_later["score_compare"] / (
        #     compare_earlier_later["score_later"]
        #     + compare_earlier_later["score_earlier"]
        # )
        # compare_earlier_later["score"] = compare_earlier_later[
        #     "score_compare"
        # ] / compare_earlier_later[["score_earlier", "score_later"]].max(axis=1)

        pred = compare_earlier_later.set_index("word")["score_compare"].to_dict()

        for tw in target_words:
            v1.append(gold_data_change_graded[tw])
            v2.append(-1 * pred[tw])

        spr, _ = spearmanr(v1, v2)
        print(spr)

2024-10-24 09:56:49,672 - INFO - loading data from ../input/llama3.1-8B/dwug_en/fs ...
2024-10-24 09:56:49,783 - INFO - data loaded ...

dwug_en:
  llama3.1-8B:

2024-10-24 09:56:50,890 - INFO - loading data from ../input/mixtral-8xtb-v0.1/dwug_en/fs ...
2024-10-24 09:56:51,003 - INFO - data loaded ...

0.3815508762721393
  mixtral-8xtb-v0.1: 0.525492070739006

In [27]:
path_to_results = "../cv-apd-experiments-lscd-xl-lexeme/xl-lexeme"
dataset = "dwug_es"

In [28]:
p = Path(path_to_results)
assert p.exists() is True

In [29]:
data_to_be_concatenated = []

for d in Path(p / f"{dataset}").iterdir():
    if d.is_dir():
        data = pd.read_csv(f"{d}/results_testing_set.csv")
        data_to_be_concatenated.append(data)

In [30]:
data = pd.concat(data_to_be_concatenated, axis=0, ignore_index=True)
display(data)

             word       apd          parameters
0        historia -0.628900  {'prompt': 'wic1'}
1           disco -0.567466  {'prompt': 'wic1'}
2           tarea -0.852457  {'prompt': 'wic1'}
3        recordar -0.736767  {'prompt': 'wic1'}
4          maduro -0.546741  {'prompt': 'wic1'}
5     susceptible -0.594091  {'prompt': 'wic1'}
6       compasión -0.885338  {'prompt': 'wic1'}
7           prima -0.626936  {'prompt': 'wic1'}
8        tropical -0.807608  {'prompt': 'wic1'}
9           matiz -0.711944  {'prompt': 'wic1'}
10         cobrar -0.492511  {'prompt': 'wic1'}
11        capital -0.573380  {'prompt': 'wic1'}
12    propiamente -0.646138  {'prompt': 'wic1'}
13         médula -0.713055  {'prompt': 'wic1'}
14       ausencia -0.575862  {'prompt': 'wic1'}
15    historiador -0.911487  {'prompt': 'wic1'}
16        actitud -0.769373  {'prompt': 'wic1'}
17        impulso -0.704866  {'prompt': 'wic1'}
18      solicitud -0.644012  {'prompt': 'wic1'}
19       variedad -0.767501  {'prompt': 'wic1'}
20     recomendar -0.738078  {'prompt': 'wic1'}
21      colaborar -0.830110  {'prompt': 'wic1'}
22         fallar -0.595532  {'prompt': 'wic1'}
23         ataque -0.735464  {'prompt': 'wic1'}
24       declinar -0.526367  {'prompt': 'wic1'}
25     retroceder -0.645799  {'prompt': 'wic1'}
26      elocuente -0.743012  {'prompt': 'wic1'}
27           demá -0.544523  {'prompt': 'wic1'}
28     indicativo -0.647140  {'prompt': 'wic1'}
29     diligencia -0.533793  {'prompt': 'wic1'}
30          canal -0.524445  {'prompt': 'wic1'}
31          trato -0.678350  {'prompt': 'wic1'}
32     socialista -0.717716  {'prompt': 'wic1'}
33        viernes -0.916750  {'prompt': 'wic1'}
34        próximo -0.552736  {'prompt': 'wic1'}
35     distribuir -0.767396  {'prompt': 'wic1'}
36        juguete -0.819896  {'prompt': 'wic1'}
37      pendiente -0.476527  {'prompt': 'wic1'}
38        educado -0.782582  {'prompt': 'wic1'}
39           pila -0.566428  {'prompt': 'wic1'}
40        vuestro -0.383384  {'prompt': 'wic1'}
41    maravilloso -0.846540  {'prompt': 'wic1'}
42      encargado -0.813740  {'prompt': 'wic1'}
43         avance -0.631742  {'prompt': 'wic1'}
44          atrás -0.584788  {'prompt': 'wic1'}
45         planta -0.511764  {'prompt': 'wic1'}
46         visita -0.778588  {'prompt': 'wic1'}
47   especulación -0.605574  {'prompt': 'wic1'}
48          metal -0.759505  {'prompt': 'wic1'}
49          banco -0.570660  {'prompt': 'wic1'}
50     modificado -0.758932  {'prompt': 'wic1'}
51      corriente -0.528044  {'prompt': 'wic1'}
52         copiar -0.719028  {'prompt': 'wic1'}
53        enterar -0.865391  {'prompt': 'wic1'}
54          metro -0.809490  {'prompt': 'wic1'}
55          marco -0.571082  {'prompt': 'wic1'}
56         cólera -0.746131  {'prompt': 'wic1'}
57  fallecimiento -0.865665  {'prompt': 'wic1'}
58        nombrar -0.690750  {'prompt': 'wic1'}
59       satélite -0.550387  {'prompt': 'wic1'}

In [31]:
predictions = data.set_index("word")["apd"].to_dict()
predictions

{'historia': -0.6288996900976294,
 'disco': -0.5674661575984815,
 'tarea': -0.8524568542456012,
 'recordar': -0.7367671162654189,
 'maduro': -0.5467409810334821,
 'susceptible': -0.5940907165171605,
 'compasión': -0.8853378078112233,
 'prima': -0.6269358259745129,
 'tropical': -0.8076077760707261,
 'matiz': -0.7119443034210039,
 'cobrar': -0.4925112644831336,
 'capital': -0.5733796368042624,
 'propiamente': -0.6461378140096808,
 'médula': -0.7130548354179137,
 'ausencia': -0.5758617650642083,
 'historiador': -0.911486922191972,
 'actitud': -0.7693728639529299,
 'impulso': -0.7048655375938825,
 'solicitud': -0.6440119474575152,
 'variedad': -0.7675014764791189,
 'recomendar': -0.7380784560472534,
 'colaborar': -0.830110381965447,
 'fallar': -0.5955320803018712,
 'ataque': -0.7354644097779923,
 'declinar': -0.5263670903749951,
 'retroceder': -0.645799008546731,
 'elocuente': -0.7430115632521798,
 'demá': -0.5445232982818893,
 'indicativo': -0.647139639808581,
 'diligencia': -0.533793354526183,
 'canal': -0.5244450492736616,
 'trato': -0.6783501589145413,
 'socialista': -0.7177162619835549,
 'viernes': -0.9167503006947344,
 'próximo': -0.5527358634349623,
 'distribuir': -0.7673958471286005,
 'juguete': -0.8198963970710067,
 'pendiente': -0.476527081468166,
 'educado': -0.7825815965611278,
 'pila': -0.5664279395189037,
 'vuestro': -0.3833843749303079,
 'maravilloso': -0.8465397098125552,
 'encargado': -0.8137397779104034,
 'avance': -0.6317419311399984,
 'atrás': -0.5847882011480494,
 'planta': -0.5117641390134122,
 'visita': -0.7785879897202554,
 'especulación': -0.6055741500040542,
 'metal': -0.7595050094219351,
 'banco': -0.5706595188049487,
 'modificado': -0.7589323351307518,
 'corriente': -0.5280441748790248,
 'copiar': -0.7190281985298032,
 'enterar': -0.865391076986606,
 'metro': -0.8094895435430922,
 'marco': -0.5710816070457536,
 'cólera': -0.7461309260282758,
 'fallecimiento': -0.8656652474603729,
 'nombrar': -0.6907496065665512,
 'satélite': -0.5503870448889802}

In [32]:
v1, v2 = [], []

In [33]:
for tw in target_words_spanish:
    v1.append(gold_data_spanish_change_graded[tw])
    v2.append(predictions[tw])

assert len(v1) == len(v2)

In [34]:
spr, _ = spearmanr(v1, v2)
spr

0.46150158497116023

In [35]:
assert p.exists() is True
print(p)

../cv-apd-experiments-lscd-xl-lexeme/xl-lexeme

In [36]:
dataset = "dwug_en"

In [37]:
data_to_be_concatenated = []

for d in Path(p / f"{dataset}").iterdir():
    if d.is_dir():
        data = pd.read_csv(f"{d}/results_testing_set.csv")
        data_to_be_concatenated.append(data)

In [38]:
data = pd.concat(data_to_be_concatenated, axis=0, ignore_index=True)
display(data)

                word       apd          parameters
0            part_nn -0.565432  {'prompt': 'wic1'}
1          attack_nn -0.692126  {'prompt': 'wic1'}
2             pin_vb -0.594366  {'prompt': 'wic1'}
3            lass_nn -0.706836  {'prompt': 'wic1'}
4           twist_nn -0.497280  {'prompt': 'wic1'}
5           graft_nn -0.566881  {'prompt': 'wic1'}
6            stab_nn -0.531856  {'prompt': 'wic1'}
7             tip_vb -0.473749  {'prompt': 'wic1'}
8       multitude_nn -0.810607  {'prompt': 'wic1'}
9           plane_nn -0.484054  {'prompt': 'wic1'}
10           face_nn -0.787024  {'prompt': 'wic1'}
11          thump_nn -0.682459  {'prompt': 'wic1'}
12           head_nn -0.619198  {'prompt': 'wic1'}
13         stroke_vb -0.750776  {'prompt': 'wic1'}
14           lane_nn -0.716654  {'prompt': 'wic1'}
15           land_nn -0.662977  {'prompt': 'wic1'}
16            rag_nn -0.715951  {'prompt': 'wic1'}
17  contemplation_nn -0.757792  {'prompt': 'wic1'}
18          ounce_nn -0.853159  {'prompt': 'wic1'}
19           risk_nn -0.913268  {'prompt': 'wic1'}
20        fiction_nn -0.829038  {'prompt': 'wic1'}
21         donkey_nn -0.828382  {'prompt': 'wic1'}
22         savage_nn -0.700884  {'prompt': 'wic1'}
23           prop_nn -0.589809  {'prompt': 'wic1'}
24            gas_nn -0.756964  {'prompt': 'wic1'}
25           ball_nn -0.605913  {'prompt': 'wic1'}
26           word_nn -0.798594  {'prompt': 'wic1'}
27         player_nn -0.702347  {'prompt': 'wic1'}
28   relationship_nn -0.733074  {'prompt': 'wic1'}
29       chairman_nn -0.887096  {'prompt': 'wic1'}
30           edge_nn -0.672444  {'prompt': 'wic1'}
31            bag_nn -0.801927  {'prompt': 'wic1'}
32            bit_nn -0.655763  {'prompt': 'wic1'}
33          quilt_nn -0.768765  {'prompt': 'wic1'}
34           tree_nn -0.880017  {'prompt': 'wic1'}
35         circle_vb -0.727835  {'prompt': 'wic1'}
36         record_nn -0.571594  {'prompt': 'wic1'}

In [39]:
predictions = data.set_index("word")["apd"].to_dict()
predictions

{'part_nn': -0.5654316902777834,
 'attack_nn': -0.69212647807658,
 'pin_vb': -0.5943656636752073,
 'lass_nn': -0.706836208943927,
 'twist_nn': -0.4972803114765494,
 'graft_nn': -0.5668805234130294,
 'stab_nn': -0.5318560872925118,
 'tip_vb': -0.4737491887505295,
 'multitude_nn': -0.8106072426561133,
 'plane_nn': -0.4840536353308429,
 'face_nn': -0.7870237732922011,
 'thump_nn': -0.6824585960868937,
 'head_nn': -0.6191983901724027,
 'stroke_vb': -0.7507760113394198,
 'lane_nn': -0.7166536035292534,
 'land_nn': -0.6629770018227733,
 'rag_nn': -0.7159512147559264,
 'contemplation_nn': -0.7577919804001572,
 'ounce_nn': -0.8531593414589368,
 'risk_nn': -0.9132676210949718,
 'fiction_nn': -0.8290378717202036,
 'donkey_nn': -0.8283823141470322,
 'savage_nn': -0.7008842518322133,
 'prop_nn': -0.5898088903642774,
 'gas_nn': -0.7569636521345273,
 'ball_nn': -0.6059129754442661,
 'word_nn': -0.7985938503339104,
 'player_nn': -0.702347474620737,
 'relationship_nn': -0.7330736134579432,
 'chairman_nn': -0.8870961270440162,
 'edge_nn': -0.6724435952949762,
 'bag_nn': -0.8019273267966901,
 'bit_nn': -0.6557626489436986,
 'quilt_nn': -0.7687653166454862,
 'tree_nn': -0.8800169535378114,
 'circle_vb': -0.7278348903560158,
 'record_nn': -0.5715944099926256}

In [40]:
v1, v2 = [], []

In [41]:
for tw in target_words:
    v1.append(gold_data_change_graded[tw])
    v2.append(predictions[tw])

assert len(v1) == len(v2)

In [42]:
spr, _ = spearmanr(v1, v2)
spr

0.8565331044717012

## Working on Gold Data

In [43]:
p = "../input/gold_data_minus_one/{dataset}/gold_annotated_data.scores"

In [44]:
for d in ["dwug_es", "dwug_en"]:
    q = Path(p.format(dataset=d))

    v1, v2 = [], []

    assert q.exists() is True

    data = pd.read_csv(q)
    if d == "dwug_en":
        data = data.apply(lambda row: build_id(row), axis=1)

    if d == "dwug_es":
        tws = target_words_spanish
        gds = gold_data_spanish_change_graded
    else:
        tws = target_words
        gds = gold_data_change_graded

    stats = {}

    mask_compare = (
        (data["identifier1"].str.split("_").str[0] == "old")
        & (data["identifier2"].str.split("_").str[0] != "old")
    ) | (
        (data["identifier1"].str.split("_").str[0] != "old")
        & (data["identifier2"].str.split("_").str[0] == "old")
    )

    data_filtered = data[mask_compare]
    # display(data_filtered)

    for tw in tws:
        mask = data_filtered["word"] == tw
        data_filtered_by_word = data_filtered[mask]

        avg = data_filtered_by_word["score"].mean()
        
        stats[tw] = avg

        v1.append(gds[tw])
        v2.append(-1 * avg)

    assert len(v1) == len(v2), "vector's dimensions must be equal"

    spr, _ = spearmanr(v1, v2)

    print(f"{d}: {spr}")

dwug_es: 0.9205008157896195
dwug_en: 0.9468816960563405

In [49]:
p = "../cv-experiments-lscd-gold-data-point-seven/{method}/gold_data/{dataset}"

In [50]:
for method in ["ac", "sc", "wsbm"]:
    print(f"{method}:")

    for dataset in ["dwug_es", "dwug_en"]:
        print(f"  {dataset}:", end=" ")
        q = Path(p.format(method=method, dataset=dataset))
        assert q.exists() is True
        
        data_to_be_concatenated = []
        for d in q.iterdir():
            if d.is_dir():
                data_to_be_concatenated.append(pd.read_csv(f"{d}/results_testing_set.csv"))
                
        data = pd.concat(data_to_be_concatenated, axis=0, ignore_index=True)
        predictions = data.set_index("word")["jsd"].to_dict()
        
        v1, v2 = [], []
        if dataset == "dwug_es":
            tws = target_words_spanish
            gds = gold_data_spanish_change_graded
        else:
            tws = target_words
            gds = gold_data_change_graded
            
        for tw in tws:
            v1.append(gds[tw])
            v2.append(predictions[tw])
            
        assert len(v1) == len(v2)
        
        spr, _ = spearmanr(v1, v2)
        
        print(spr)

ac:
  dwug_es: 0.18457112805930007
  dwug_en: -0.06486037927932085
sc:
  dwug_es: 0.12167079775220352
  dwug_en: -0.10244249754478817
wsbm:
  dwug_es: 0.1816558529646417
  dwug_en: 0.8612758126913672